### ISSUE TITLE
Wrong repository linked from https://pypi.python.org/pypi/Xapiand

### ISSUE THREAD

**Issue by buriy** [Kronuz/Xapiand#1]
You have wrong repository linked from https://pypi.python.org/pypi/Xapiand

**Comment by Kronuz** [comment]
Oh, you are right! I renamed the repository a while back to pyXapiand. This is the C++ rewrite with a bunch of new features... but it still isn't ready yet.

I'll fix the link in the next release. Thank you!

**Comment by buriy** [comment]
Better to fix link right now, and do release later ;)

**Comment by buriy** [comment]
Do you know you can edit pypi description text for every published release?
