### ISSUE TITLE
Add Xapiand production ready docker container

### ISSUE THREAD

**Issue by vit1251** [Kronuz/Xapiand#12]
Most popular solution ElasticSearch provide Docker container production ready on https://hub.docker.com/_/elasticsearch

How about create some similar solution and provide user simple way to try Xapiand?

**Comment by Kronuz** [comment]
I absolutely agree... but what are the differences in that image, vs our own Docker image?

**Comment by vit1251** [comment]
Current Docker container store index inside container and it lost data when stop or restart container. May be use `VOLUME` to store index on host machine? Do u have benchmark and get any performance issue with `VOLUME` in Docker?

**Comment by cbess** [comment]
As far as I can tell, you can use the `-v` option to mount the `/var/db/xapiand/` directory on the host. It worked for me. However, restarting the container is a different issue:
> Node name 6f9e78432364 doesn't match with the one in the cluster's database!

How do I provide the node name upon startup?

Mount option:
> -v /my/host/dir/xapiand:/var/db/xapiand

Full example:
```bash
docker run -p 8880:8880 -v /my/host/dir/xapiand:/var/db/xapiand --rm dubalu/xapiand:0.22.0 -vvv
```

BTW, many thanks @Kronuz for sharing this project! I'm loving the potential of seeing a viable and easy to setup ElasticSearch and Sphinxsearch alternative! Great codebase as well!

**Comment by Kronuz** [comment]
Thank you @cbess.
You can use `--name NodeName` as a parameter (or it should work) you can also set the `XAPIAND_NAME` environment variable. The default for the node name in Docker is the host name, so you probably can also request Docker to use a different hostname.

**Comment by cbess** [comment]
Awesome, I just tested it, worked perfectly! Thanks for the prompt response. I'm definitely excited to see this project become more visible!

Working command to have persistent Xapiand data in Docker:
```bash
docker run -p 8880:8880 -v /tmp/xapiand:/var/db/xapiand --rm dubalu/xapiand:0.22.0 -vvv --name myxapiand
```

@vit1251 Looks like we don't need any modifications for persistent data.

**Comment by cbess** [comment]
I think this can be closed out.
