### ISSUE TITLE
Listing of indices

### ISSUE THREAD

**Issue by geostarling** [Kronuz/Xapiand#15]
Is there a way to list all indices that are currently available in the cluster without prior knowledge of their names?
I was unable to find this information in the documentation.

Thank you.

**Comment by Kronuz** [comment]
Yes, indices are added to the `.xapiand/index` index (might change to `.xapiand/indices` in the next version). In there, besides it’s name (which is the `_id`), there is also the schema and other settings. You can use: `SEARCH /.xapiand/index`. Note, however, that it’s not recommended to do direct writes to that index.

**Comment by Kronuz** [comment]
I forgot to mention, `.xapiand/index` index contains all and each shard in the system, and so, because indices have 5 shards by default, you’ll see indices there look “duplicated” only differing by the ending (`some/index`, `some/index/.__1`, `some/index/.__2`, ...)

**Comment by Kronuz** [comment]
The indices database did get renamed to indices, so it's now `.xapiand/indices`.

Something like `curl -vX SEARCH 'localhost:8880/.xapiand/indices/?echo&pretty&comments&volatile'` gets all indices in the cluster.
