### ISSUE TITLE
How to make AND the default boolean operator (instead of OR)?

### ISSUE THREAD

**Issue by ngrilly** [Kronuz/Xapiand#20]
When sending a search query like `{"_query": {"fieldname": "hello world"}}` through the SEARCH HTTP method, the default boolean operator between "hello" and "world" is OR. 

Is it possible to make AND the default? (like with `Xapian::QueryParser::set_default_op(Xapian::Query::OP_AND`)

**Comment by YosefMac** [comment]
This should work:
```
{ "_query": {"fieldname": { "_and": "hello world"} } }
```

**Comment by ngrilly** [comment]
Yes, it works, but then I loose the ability to use an explicit OR between
terms.

For example:

`{ "_query": {"fieldname": { "_and": "hello OR world"}`

**Comment by YosefMac** [comment]
[Docs](https://kronuz.io/Xapiand/docs/reference-guide/search/query-dsl/compound-queries/logical-operators/) I guess this is what you looking for:

```
{
  "_query": {
    "_or": [
      {
        "fieldname": "hello"
      },
      {
        "fieldname": "world"
      }
    ]
  }
}
```

**Comment by ngrilly** [comment]
I realize my answer wasn't clear.

The query string is provided by the end user. I want it to be parsed by Xapiand, using the equivalent of Xapian::QueryParser, with the default boolean operator being AND instead of OR.

This means the query string "hello world" should be equivalent to "hello AND world" (implicit AND between words). But the user should also be able to search "hello OR world".

**Comment by YosefMac** [comment]
I think I'm still without understand. The search "hello OR world" is done by the example above, but you have to use `_or`explicitly. 

The query user must be in the way of  [QueryDSL](https://kronuz.io/Xapiand/docs/reference-guide/search/query-dsl/) .

We don't use Xapian::QueryParser except when the type is `text` and only for add stemming and others stuff.

The must similar thing that you can do is send query params in the SEARCH method rather that the json body with QueryDSL. Something like this:

`SEARCH /mydb/?q=fieldname:hello%20OR%20fieldname:world`

But we discourage use of this way because at the end is parsed to QueryDSL form, and just add overhead and in the future versions perhaps is not supported.

**Comment by ngrilly** [comment]
I'm working on an app in which the end user can enter a search query in a standard text field widget.

A query can be as simple as `hello world` or as complex as `apple AND a NEAR word OR "a phrase" NOT (too difficult) +eh`. This is why I'd like to reuse the syntax of `Xapian::QueryParser`. More info [here](https://getting-started-with-xapian.readthedocs.io/en/latest/concepts/search/queryparser.html).

And I cannot ask the end user to express the query as a JSON object representing an Abstract Syntax Tree ;-)

**Comment by YosefMac** [comment]
For this case you can use the SEARCH method and send the user query `hello OR world` in the request query param and use the index mode `"_index": "terms"` this allow search without the field and the query syntax is going to be more like you looking for:

` SEARCH /mydb/?query=hello OR world`

The logical operators that are supported in this mode are: AND, MAYBE, OR, NOT, XOR. This also support use of parenthesis for operator precedence, the phrases are supported as well but not `+/-` operators

**Comment by ngrilly** [comment]
I've upgraded to v0.29.0. `SEARCH /mydb/?query=hello OR world` and `SEARCH /mydb/?query=hello AND world` work now. But `SEARCH /mydb/?query=hello world` (without any boolean operator between words) fails with this message: `Bad Request: Bad boolean expression`.

**Comment by YosefMac** [comment]
Yes, there wasn't implicit default operator in this query mode. Should work in 460c8d9. Thanks again for the report!!
