### ISSUE TITLE
Option to store (or not store) field

### ISSUE THREAD

**Issue by dgllghr** [Kronuz/Xapiand#22]
I just discovered this project and it looks fantastic! Thank you for building it.

After looking through the docs, I didn't see a way to specify whether the value for a field should be stored or not. It looks like all values are always stored. Being able to index fields without storing the value is useful for indexing external data, and I think it would be a good addition to this project.

**Comment by Kronuz** [comment]
Thank you, we're glad you find the project useful!

By default, fields are stored, to force a field not to be stored, use `"_store": false` in the field definition. Note, however, that documents with fields which are not stored cannot be fully reindexed without the original document data.
