### ISSUE TITLE
Limiting Returned Fields on Query

### ISSUE THREAD

**Issue by lodestone** [Kronuz/Xapiand#3]
I followed the instructions here: <https://kronuz.io/Xapiand/docs/exploring/>

When I executed the following curl command, I didn't get back only the `account_number` and `balance` fields though. It appears to return the whole document.

```sh
curl -H 'Content-Type: application/json' --data-binary '{
  "_query": "*",
  "_source": ["account_number", "balance"]
}' -X GET 'localhost:8880/bank/:search?pretty'
```

How can I limit the fields returned?

**Comment by Kronuz** [comment]
That part of the documentation needs updating as those examples are not working...

**Comment by lodestone** [comment]
Is it still currently possible to limit the returned fields or did that get removed? 

I'd love to help update the docs but I don't know C/C++ very well so I don't know where to look for the logic...

**Comment by Kronuz** [comment]
Yes, it is possible, but I’ll have to check the source code to make sure.

From the top of my head, there are two ways of filtering fields:

One is using dot(s) for getting a nested field value (drilling):

```http
GET /bank/:search|account_number?pretty'
```

and one is using object selector:

```http
GET /bank/:search{account_number,balance}?pretty'
```
