### ISSUE TITLE
Is there any document explaining the config of xapiand?

### ISSUE THREAD

**Issue by zhanglistar** [Kronuz/Xapiand#30]
I have read the documents on website, but found nothing saying about the configuration of xapiand.

**Comment by Kronuz** [comment]
Configuration is don't using command options: https://kronuz.io/Xapiand/docs/options however, the information there is incomplete. Best bet is still using `xapiand --help` and digging in the source code...

We should work on this, explaining each and every option. Maybe perhaps also adding a way to configure Xapiand using a configuration file of some sort (perhaps json or yaml).

**Comment by zhanglistar** [comment]
> Configuration is don't using command options: https://kronuz.io/Xapiand/docs/options however, the information there is incomplete. Best bet is still using `xapiand --help` and digging in the source code...
> 
> We should work on this, explaining each and every option. Maybe perhaps also adding a way to configure Xapiand using a configuration file of some sort (perhaps json or yaml).

Thanks for your reply.
