### ISSUE TITLE
Compile on Debian complete with error

### ISSUE THREAD

**Issue by vit1251** [Kronuz/Xapiand#8]
Can I suggest you start using CI system for example TravisCI or CircleCI service?
It may increase source code quality and provide Debian package for example.

```
In file included from /opt/Xapiand/src/msgpack_patcher.cc:23:
In file included from ../src/msgpack_patcher.h:31:
In file included from ../src/exception.h:42:
In file included from ../src/fmt/format.h:60:
../src/fmt/core.h:541:3: error: static_assert failed "don't know how to format the type, include fmt/ostream.h if it provides an operator<< that should be used"
  static_assert(
  ^
../src/fmt/core.h:677:15: note: in instantiation of template class 'fmt::v5::internal::fallback_formatter<std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> >, char, void>' requested here
    Formatter f;
              ^
../src/fmt/core.h:663:22: note: in instantiation of function template specialization 'fmt::v5::internal::value<fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >::format_custom_arg<std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> >, fmt::v5::internal::fallback_formatter<std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> >, char, void> >' requested here
    custom.format = &format_custom_arg<
                     ^
../src/fmt/core.h:690:58: note: in instantiation of function template specialization 'fmt::v5::internal::value<fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >::value<std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > >' requested here
  FMT_CONSTEXPR operator value<Context>() const { return value<Context>(val); }
                                                         ^
../src/fmt/core.h:1249:25: note: in instantiation of function template specialization 'fmt::v5::internal::make_arg<true, fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>, std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > >' requested here
      : data_{internal::make_arg<IS_PACKED, Context>(args)...} {}
                        ^
../src/fmt/core.h:1269:10: note: in instantiation of member function 'fmt::v5::format_arg_store<fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>, const char *, std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > >::format_arg_store' requested here
  return {args...};
         ^
../src/exception.h:83:90: note: in instantiation of function template specialization 'fmt::v5::make_format_args<fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>, const char *, std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > >' requested here
                : BaseException(private_ctor{}, default_exc(), function, filename, line, type, format, make_format_args(std::forward<Args>(args)...)) { }
                                                                                                       ^
../src/exception.h:219:36: note: in instantiation of function template specialization 'BaseException::BaseException<const char *const &, const std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > &>' requested here
        InvalidArgument(Args&&... args) : BaseException(std::forward<Args>(args)...), std::invalid_argument(message) { }
                                          ^
../src/strict_stox.hh:101:11: note: in instantiation of function template specialization 'InvalidArgument::InvalidArgument<char const (&)[11], char const (&)[22], int, char const (&)[16], char const (&)[29], const char *const &, const std::experimental::fundamentals_v1::basic_string_view<char, std::char_traits<char> > &>' requested here
                                THROW(InvalidArgument, "{}: Cannot convert value: {}", name, str);
                                      ^
3 errors generated.
ninja: build stopped: subcommand failed.
```

**Comment by Kronuz** [comment]
That’s odd. What compiler are you using?

I certainly would love to add CI; Travis CI is what I’ve used, but I’m all alone in this project, mostly, and I honestly have very little time left.

**Comment by vit1251** [comment]
>  That’s odd. What compiler are you using?

I make apt install cmake, clang, git and few another package and doing cmake by you compile instruction. Actually I does not know what compiler cmake use in result. I think that cmake using one of gcc or clang.

> Travis CI is what I’ve used ...

It take a totally small amount of time to make yaml script with TravisCI but you should be ready that on TravisCI provide extrem outdate version of Ubuntu server packges.

**Comment by Kronuz** [comment]
@vit1251 I made a few changes in the CMakeLists.txt file, I'm now specifying c++17 and also properly including `<string_view>`... If you have some time, I'd appreciate if you could try compiling the latest now (v0.15.0).

It'd also be great if you could put together a TravisCI script so we can add it to the repo and have it building stuff, it'd be a great addition to have that working.

**Comment by vit1251** [comment]
@Kronuz hello again. I fork your repository and make Travis compilation descriptor.
You may review result in https://travis-ci.org/vit1251/Xapiand/jobs/510183250#L6
It look like Ubuntu 14 does not provide C++17 compiler. You actually use C++17
features?

**Comment by Kronuz** [comment]
I’m using string_view from c++17

**Comment by vit1251** [comment]
I have better result. But as you can see still with errors.
Please see https://travis-ci.org/vit1251/Xapiand/jobs/510189758
What your workstation gcc version? Or you use clang?

**Comment by Kronuz** [comment]
I’m using clang with libc++

**Comment by vit1251** [comment]
What you version of clang?

**Comment by Kronuz** [comment]
I’ve used clang 4 (apple clang) and clang 7

**Comment by vit1251** [comment]
Yey. Scored. But right now no includes https://travis-ci.org/vit1251/Xapiand/jobs/510193502

**Comment by vit1251** [comment]
One step before win here https://travis-ci.org/vit1251/Xapiand/jobs/510194224

**Comment by Kronuz** [comment]
Yes, apparently it now has missing includes, for some reason...

**Comment by vit1251** [comment]
Any idea about shadow here https://travis-ci.org/vit1251/Xapiand/jobs/510196143 ?

**Comment by vit1251** [comment]
I have no more compile way. I can also check update in clang on version 8.
But as you can see Ubuntu with many compiler combination like gcc-6, gcc-7 and clang-7 does not provide repeatable success compilation.

**Comment by Kronuz** [comment]
What it’d be awesome is to make it compile with GCC and libstdc++ as well

**Comment by Kronuz** [comment]
That thing about shadowed local variable is, I'm sure, the implementation of `htobe64` and `be64toh` which in that linux machine are using `bswap_64` from `byteswap.h`, expanding to declare the same nested variable names... (effectively shadowing a local variable, which is warned and in Release mode of Xapiand also an error (-Werror)). Maybe splitting https://github.com/Kronuz/Xapiand/blob/master/src/cuuid/uuid.cc#L429 into two lines would help:

```c++
	uint64_t hnode = be64toh(*node_ptr) & 0xffff000000000000ULL;
	*node_ptr = htobe64(hnode | (node & 0xffffffffffffULL));
```

**Edit:** Pushed a commit for this one.

**Comment by vit1251** [comment]
OK. I will try at evening compile with gcc-6, gcc-7 and gcc-8 instead clang.

**Comment by Kronuz** [comment]
It’s now compiling fine with clang (except linker is failing)... but apparently compiling with GCC will need more work

**Comment by Kronuz** [comment]
I’ve pulled the TravisCI you added and it’s now compiling fine. What would be next towards having a Debian package everyone could easily install?

**Comment by vit1251** [comment]
Yep. I think we need a different issue about Debian package.

**Comment by Kronuz** [comment]
I agree. We’re done adding TravisCI, thank you!
