### ISSUE TITLE
Bulk Insert/Update API

### ISSUE THREAD

**Issue by geostarling** [Kronuz/Xapiand#9]
Hi!

I'm trying to setup a syslog message forwarding with Xapiand as a target. Syslog server implementation (rsyslog) performs message batching by default, so I'm wondering if there is an option for bulk insert/update of data via Xapiand's API. And if there is not, are there any blockers that would prevent such a functionality in Xapiand (I'm not familiar with libxapian internals).

Thanks a lot.

**Comment by Kronuz** [comment]
Yes, there is, you can use `:restore`, here is an example: https://kronuz.io/Xapiand/docs/exploring/#loading-the-sample-dataset

**Comment by geostarling** [comment]
Thank you for the answer.
I've tried the examples you've linked but I'm getting some strange behaviour of restore functionality.

When I try to restore sample dataset (accounts.ndjson) as shown in example, the response code is `200 OK` but actual resonse body shows 0 indexed documents (see below).

```
 curl -v -H 'Expect:'  -X POST -H 'Content-Type: application/x-ndjson' -d@/tmp/accounts.ndjson 'http://localhost:8880/bank/:restore?pretty'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8880 (#0)
> POST /bank/:restore?pretty HTTP/1.1
> Host: localhost:8880
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/x-ndjson
> Content-Length: 1314686
>
* We are completely uploaded and fine
< HTTP/1.1 200 OK
< Server: Xapiand v0.14.0_20190312201201 (2427bdf)
< Database: xapian://172.17.0.2:9880/bank
< Response-Time: 0.052745
< Operation-Time: 3e-6
< Content-Type: application/json; charset=utf-8
< Content-Length: 85
<
{
  "processed": 0,
  "indexed": 0,
  "total": 0,
  "items": [],
  "took": "3.0µs"
* Connection #0 to host localhost left intact
```

When I try to query index metadata I get 404 as no documents were actually inserted.

```
curl -v -X GET 'http://localhost:8880/bank/:info?pretty'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8880 (#0)
> GET /bank/:info?pretty HTTP/1.1
> Host: localhost:8880
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: Xapiand v0.14.0_20190312201201 (2427bdf)
< Database: xapian://172.17.0.2:9880/bank
< Response-Time: 0.001223
< Content-Type: application/json; charset=utf-8
< Content-Length: 57
<
{
  "#status": 404,
  "#message": [
    "Not Found"
  ]
* Connection #0 to host localhost left intact
```


When I try to restore reduced dataset, the cause becomes more apparent:
accounts-short.ndjson:

```
{"accountNumber": 121931, "balance": 221.46}
{"accountNumber": 148040, "balance": 1494.65}
```

same HTTP response from server:

```
curl -v -H 'Expect:'  -X POST -H 'Content-Type: application/x-ndjson' -d@/tmp/accounts-short.ndjson 'http://localhost:8880/bank/:restore?pretty'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8880 (#0)
> POST /bank/:restore?pretty HTTP/1.1
> Host: localhost:8880
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/x-ndjson
> Content-Length: 89
>
* upload completely sent off: 89 out of 89 bytes
< HTTP/1.1 200 OK
< Server: Xapiand v0.14.0_20190312201201 (2427bdf)
< Database: xapian://172.17.0.2:9880/bank
< Response-Time: 0.000492
< Operation-Time: 4e-6
< Content-Type: application/json; charset=utf-8
< Content-Length: 85
<
{
  "processed": 0,
  "indexed": 0,
  "total": 0,
  "items": [],
  "took": "4.0µs"
```

In xapiand output I see following error:

```
▊20190319150426 Cannot load object: ../src/database_utils.cc:165 at json_load: JSON parse error at line 1, col: 45 : The document root must not be followed by other values.
1. {"accountNumber": 121931, "balance": 221.46}{"accountNumber": 148040, "balance": 1494.65}
                                               ^
```

So there seems to be some issue with JSON payload splitting but I was unable to find the exact cause. Also, the fact that failed import (restore) is not propagated to the client is problematic for my use case.

I'm using docker image of Xapiand 0.14.0 but I've observed same problem with non-dockerized 0.10.0 version.

Any ideas?

**Comment by Kronuz** [comment]
You should be using `--data-binary`, as ndjson requires receiving line breaks:

```sh
curl -v -X POST -H 'Content-Type: application/x-ndjson' --data-binary @/tmp/accounts.ndjson 'http://localhost:8880/bank/:restore?pretty'
```

**Comment by Kronuz** [comment]
Also, note I’ll be releasing v0.15.0 with breaking changes in the schema and quite a few optimizations very soon

**Comment by geostarling** [comment]
That did the trick! Thank you.

> Also, note I’ll be releasing v0.15.0 with breaking changes in the schema and quite a few optimizations very soon

Yes, I'm aware of potential breaking changes. I'm attempting to use Xapiand for some non-essential data (as an alternative to elastic) at the moment. So far, it looks very promising.
